---
- name: Install and configure Nginx and PHP-FPM
  hosts: web-server
  become: true
  tasks:
    - name: Install Nginx and PHP-FPM
      dnf:
        name: ['nginx', 'php-fpm']
        state: present
    - name: Copy config files
      copy:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      loop:
        - src: /home/sokar/Pulpit/Exe/playbooks/info.php
          dest: /usr/share/nginx/html/info.php
        - src: /home/sokar/Pulpit/Exe/playbooks/dev.service
          dest: /etc/systemd/system/dev.service
        - src: /home/sokar/Pulpit/Exe/playbooks/dev.timer
          dest: /etc/systemd/system/dev.timer
        - src: /home/sokar/Pulpit/Exe/playbooks/echo_script.sh
          dest: /home/ec2-user/echo_script.sh
    - name: Make script executable
      file:
        path: /home/ec2-user/echo_script.sh
        mode: '0755'
    - name: Start services
      service:
        name: '{{ item.name }}'
        state: started
        enabled: yes
      loop:
        - name: nginx
        - name: php-fpm
        - name: dev.service
        - name: dev.timer